### ISSUE TITLE
macOS Secure Enclave Support

### ISSUE THREAD

**Issue by brianpartridge** [square/Valet#100]
With touch ID now available on macOS 10.12.1 we should confirm that Valet works with it.  [This line](https://github.com/square/Valet/blob/master/Valet/VALSecureEnclaveValet.h#L25) indicates that we have some macOS support already, but we should verify.  (I would but I'm not running 10.12 yet.)

**Comment by dfed** [comment]
We'll need to include bump `VAL_ACCESS_CONTROL_TOUCH_ID_SDK_AVAILABLE` to include MacOS 10.12.1+

**Comment by dfed** [comment]
Go figure, looks like the Touch ID SDK is available in 10.12+, not just 10.12.1+. ¯\\_(ツ)_/¯

**Comment by dfed** [comment]
This was resolved with #103
