### ISSUE TITLE
Intermittent Read Failures

### ISSUE THREAD

**Issue by jshier** [square/Valet#109]
So I have a `VALValet` as such:
```swift
static let sharedValet = VALValet(identifier: Key.identifier.rawValue, accessibility: .afterFirstUnlockThisDeviceOnly)!
```
Most of the time it works fine. However, I'm running into rare, non-repeatable read failures for values which were stored in it (which I'm sure succeed). Are there any read failure scenarios I should be aware of? There isn't really a lot of insight into why a read failed as Valet just assumes it was because the value was never there to begin with. So what are my options here?

**Comment by dfed** [comment]
Sorry to hear you're experiencing non-deterministic failures! Those are the worst. I strongly recommend reading through the [debugging tips](https://github.com/square/Valet/blob/master/README.md#debugging). Hopefully those tips cover your issue.

We'll leave this issue open for a few days just in case those tips don't help. If you need more assistance, we'll need to know:
- What `canAccessKeychain` is returning when you are encountering read (or possibly write?) failures. 
- Is the issue occurring only while attached to the debugger or when running outside of Xcode as well? 
- Is your app in the background or foreground when the failures occur?
- What version(s) of iOS are you seeing this issue on?
- What version of Xcode are you running?
- What error code is the keychain returning on a read (or write) failure? If you're using Cocoapods or submodules to integrate Valet, you can use breakpoints inside Valet to determine what error code the keychain is returning.

**Comment by jshier** [comment]
Thanks for the guidance. To answer your questions:
* It's happening in our QA builds (we aren't shipping yet), which are release builds with extra instrumentation. I can't replicate it myself, whether on device or in the simulator, which means I've never been able to capture it in the debugger. I'll add additional instrumentation so that when we fail to get a value we have more info captured before the crash (unavoidable really, as this is app state information that must be in place).
* This is an iOS 10 only app, so we've seen the crash on no value on 10.1 and 10.2, and we're using the latest Xcode 8.2.1 and Valet versions. 
* I'll add instrumentation for the background vs. foreground question, but the QA folks testing the app almost always have it in the foreground. In any case, isn't `.afterFirstUnlockThisDeviceOnly` enough to guarantee access in the background?

One other question I have is whether there's detection in the keychain for attempting to access a value while writing into the keychain for that value from another thread? I've seen crashes on accessing values that aren't ever written in the background so this is more of a general question.

**Comment by dfed** [comment]
> I'll add instrumentation for the background vs. foreground question, but the QA folks testing the app almost always have it in the foreground. In any case, isn't .afterFirstUnlockThisDeviceOnly enough to guarantee access in the background?

`afterFirstUnlockThisDeviceOnly` is enough to guarantee access in the background after the first unlock, but not before that. iOS does let you wake up an app prior to the first unlock with a push notification though, and I'm not 100% sure if you're testers are seeing the crash or if your instrumentation/reporting is alerting you to it. To avoid the "Apple woke up our app before the first unlock" problem I tend to assert that I have access to the keychain in `application:didFinishLaunching:`.

> One other question I have is whether there's detection in the keychain for attempting to access a value while writing into the keychain for that value from another thread? I've seen crashes on accessing values that aren't ever written in the background so this is more of a general question.

There's no detection of simultaneous thread read/write. However, Valet uses locks internally to ensure that there is no simultaneous read/write. Of course, this doesn't guarantee "correct" behavior as much as it guarantees always having valid/complete values. Check out our use of [VALAtomicSecItemLock](https://github.com/square/Valet/blob/c5f683edf69e5e63d35593167da1e7dedd2e9272/Valet/VALValet.m#L67) to get a more complete threading picture.

**Comment by jshier** [comment]
Our state can be updated by push, so perhaps I need additional checking for that case. I don't think our QA is testing such a case though. Additionally, while waking in the background, are view controllers initialized? Those are where the crashes are coming from, as the controllers attempt to access session state that should be there but isn't. I can't find much documentation around such a case (app launch from push after restart before the user unlocks the first time).

**Comment by dfed** [comment]
By default view controllers are initialized/installed when you're woken up in the background

**Comment by jshier** [comment]
I guess the question then is whether or not `viewDidLoad` is called on them as well, as that's when I start observing the state that can come in a push. In any case I don't think this is the issue, as the rest of the crash stack shows activity that happens in the foreground.

I'm also finding conflicting information regarding whether iOS 10 has the same behavior as previous versions regarding app launch from a push after reboot (https://forums.developer.apple.com/thread/52115)

In any event I'm uncertain what I could possibly do here. Even if I somehow block keychain access until it's available, that would seem to mean I need to refactor every single access point for the session values.

I'll see if my instrumentation turns anything up.

**Comment by dfed** [comment]
I'll re-iterate my catch-all solution for this issue: assert that you have keychain access in `application:didFinishLaunching:`. e.g. If you don't have keychain access, crash. If you don't have access to the keychain your app is likely hosed, so fail early.

If you are unable to access the keychain when you think you should be able to, lmk!

**Comment by jshier** [comment]
Sorry, I didn't realize that you meant an actual assert and crash there. 💥 😄

**Comment by jshier** [comment]
I've implemented the extra instrumentation and checks, so we'll see what turns up now. 

We've also seen issues writing into the keychain, so is there anything we can do there? Specifically we're seeing a failure to write a value from a background thread during user login. It's not really something we can do without and usually works fine. Aside from the checks for keychain access I've already included, are there any additional checks to be done for writing values?

**Comment by dfed** [comment]
I'd guess your reading problem and your writing problem are the same problem. Threading should not affect writing to or reading from keychain (and as mentioned above Valet has additional protections to ensure this is the case).

You're reading/writing from/to a Valet with the same identifier/accessibility in all cases, right? Or are you using different Valets?

**Comment by jshier** [comment]
All interaction with Valet goes through this `Keychain` struct (redacted down to a single value) so I can treat store values as properties without storing them in memory. I have another similar struct for some other values. My only other state storage in the app is to a secure file on disk. This `Keychain` and the disk storage are then wrapped by a `Session` that vends the values directly.
```swift
struct Keychain {
    
    enum Key: String {
        case identifier = "AppName"
        case email
    }
    
    static let sharedValet = VALValet(identifier: Key.identifier.rawValue, accessibility: .afterFirstUnlockThisDeviceOnly)!
    
    static func clear() {
        sharedValet.removeAllObjects()
    }
    
    static var containsEmail: Bool {
        return sharedValet.containsValue(forKey: .email)
    }
    
    static var email: String? {
        get {
            return sharedValet.string(forKey: .email)
        }
        set {
            updateString(newValue, forKey: .email)
        }
    }
    
}

extension VALValet {
    
    func setString(_ string: String, forKey key: Keychain.Key) {
        guard setString(string, forKey: key.rawValue) else { fatalError("Failed to set String in VALValet due to access failure.") }
    }
    
    func string(forKey key: Keychain.Key) -> String? {
        return string(forKey: key.rawValue)
    }
    
    func setData(_ data: Data, forKey key: Keychain.Key) {
        guard setObject(data, forKey: key.rawValue) else { fatalError("Failed to set Data in VALValet due to access failure.") }
    }
    
    func data(forKey key: Keychain.Key) -> Data? {
        return object(forKey: key.rawValue)
    }
    
    func removeValue(forKey key: Keychain.Key) {
        guard removeObject(forKey: key.rawValue) else { fatalError("Failed to remove value from VALValet due to access failure.") }
    }
    
    func containsValue(forKey key: Keychain.Key) -> Bool {
        return containsObject(forKey: key.rawValue)
    }
    
}
```

**Comment by dfed** [comment]
Any updates here?

The above struct looks reasonably fine assuming that `email` does in fact have a non-zero-length backing string value.

**Comment by jshier** [comment]
I was still seeing a few crashes but we had to ship the code to the client before I could get a real data set, so I didn't have a real resolution here. Thanks for the help.
