### ISSUE TITLE
Queue behavior of TouchID prompts?

### ISSUE THREAD

**Issue by jshier** [square/Valet#110]
Prompting for TouchID using `LAContext` uses a completion handler on another queue. However, the direct prompt through the keychain (and Valet obviously), just seems to be a direct, synchronous call. Is that correct? Is there anything we need to be aware of here in regards to proper queue usage? What happens if the user doesn't confirm for 30 seconds? Is this blocking the main queue or not? Should I be wrapping these calls in my own asynchronous solution?

**Comment by dfed** [comment]
Keychain calls are indeed blocking. So calling `objectForKey:` will block whatever queue you call it on. Given that Keychain is handling the out-of-process `LAContext`/TouchID prompt under the hood though, blocking the main queue might be fine for your app: you won't end up in a deadlock just by accessing keychain.

Long story short: whether you use background queues for keychain access is entirely up to you. There's nothing stopping you from reading/writing on the main queue at face value. Do note that Valet handles locking for you under the hood, so you don't have to worry about reading garbage values out while another queue is mid-write.

Closing this issue. Feel free to ask more qs here (I'll respond I swear!) though. Alternatively, for random Keychain-related but not Valet-specific qs feel free to tweet me [@TheFederman](http://www.twitter.com/thefederman).
