### ISSUE TITLE
Change a VALValet's accessibility level

### ISSUE THREAD

**Issue by nemesis** [square/Valet#112]
Is it possible to change a specific VALValet's accessibility level?

For instance, let's say a VALValet had `.always` accessibility and now I want to make it `.afterFirstUnlock`.

The [Apple docs](https://developer.apple.com/documentation/security/ksecattraccessible) say that it's possible, and there's even some [sample code](https://stackoverflow.com/questions/5369238/is-it-possible-to-update-a-keychain-items-ksecattraccessible-value) on StackOverflow, but is there a way to do this with Valet without having to migrate to a new VALValet with different accessibility?

Thanks.

**Comment by dfed** [comment]
You can't change the accessibility level on an existing Valet. However, you can create a new Valet, and use [-migrateObjectsFromValet:removeOnCompletion:](https://github.com/square/Valet/blob/master/Valet/VALValet.h#L125) to migrate the items over when both are accessible.

Creating a new Valet is cheap, and the migration call is explicit and allows you to detect errors. We wouldn't want to create an API that implicitly migrated via changing the accessibility level. Closing this out.
