### ISSUE TITLE
Valet error when kSecAttAccount is not a String during keychain migration

### ISSUE THREAD

**Issue by kgleong** [square/Valet#113]
[kSecAttrAccount](https://developer.apple.com/documentation/security/ksecattraccount?language=objc) should be a String, but a developer can choose to store an `NSData` object there instead.

Exception:
```
2017-08-09 16:17:20.566 PaySDKDemo[9913:612370] -[__NSCFData isEqualToString:]: unrecognized selector sent to instance 0x6080002a0df0
```

Crash occurs here: https://github.com/square/Valet/blob/2.2.3/Valet/VALValet.m#L426 

Code used to reproduce crash:

```objective-c
// Add an NSData object as the kSecAttrAccount entry
NSDictionary *keychainData = @{(id)kSecAttrService: [NSBundle mainBundle].bundleIdentifier, (id)kSecClass: (id)kSecClassGenericPassword, (id)kSecAttrAccount:[@"bar" dataUsingEncoding:NSUTF8StringEncoding], (id)kSecValueData:[@"foo" dataUsingEncoding:NSUTF8StringEncoding]};

// Manually add the entry above to the keychain
__unused OSStatus status = SecItemAdd((__bridge CFDictionaryRef)keychainData, NULL);

VALValet *keychain = // initialize a Valet keychain

// ** Crash **
[keychain migrateObjectsMatchingQuery:[SQLegacyKeychain migrationQueryWithService:[NSBundle mainBundle].bundleIdentifier] removeOnCompletion:YES];
```

@EricMuller22 @dfed

**Comment by dfed** [comment]
Great find! Should be an easy fix – hopefully we can just sanity check the input. I'm a little embarrassed we weren't already doing that

**Comment by EricMuller22** [comment]
Talked offline (and paired on finding this 😂), but @kgleong is going to follow up with a unit test and fix (probably just an `isKindOfClass` check.)

**Comment by dfed** [comment]
Closing out this issue since #114 fixed it :)
