### ISSUE TITLE
Synchronizing data between a macOS and iOS app?

### ISSUE THREAD

**Issue by hankinsoft** [square/Valet#115]
I've added the following entitlement to both applications:

	<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)sharedKeychain</string>
	</array>

And I've tried the following:

iOS/app launched:

```
    valet = [[VALSynchronizableValet alloc] initWithSharedAccessGroupIdentifier: @"sharedKeychain"
                                                                           accessibility: VALAccessibilityWhenUnlocked];

    NSString * data = [valet stringForKey: @"key"];
    if(nil == data)
    {
        [valet setString: @"hello world" forKey: @"key"];
    }
```

macOS/app:

```
    valet = [[VALSynchronizableValet alloc] initWithSharedAccessGroupIdentifier: @"sharedKeychain"
                                                                           accessibility: VALAccessibilityWhenUnlocked];

    NSString * data = [valet stringForKey: @"key"];

    // Data is always nil?
```

I'm not sure why the data is coming out nil. Ive tried manually saving data on the macOS version and loading and that works fine, but I cannot seem to get the two apps to synchronize with each other. Any thoughts on what I'm doing wrong?

**Comment by dfed** [comment]
When you write the data to disk on iOS, do you see the keychain item appear in the Keychain Access application on your Mac?

**Comment by hankinsoft** [comment]
I would see this in keychain access / iCloud keychains right? I do NOT see anything appear there.

**Comment by hankinsoft** [comment]
Cross that. I do.

**Comment by dfed** [comment]
So, you're seeing it in Keychain Access on your Mac when iOS writes to the keychain (so it is syncing)... but the Mac isn't seeing it. Fascinating.

Do me a favor. On your Mac, put a breakpoint on [VALValet.m:L556](https://github.com/square/Valet/blob/master/Valet/VALValet.m#L556). When you try to pull the object that iOS put into the keychain back out, what is `copyMatchingStatus`?

Another debugging q: can the Valet on your Mac delete the object iOS put there from the keychain?

**Comment by hankinsoft** [comment]
Good morning!
So copyMatchingStatus = -25300 (errSecItemNotFound) and value = nil.

Also it seems that my original statement that the Mac could save/load data was wrong as well. Loading data when using ```VALSynchronizableValet``` returns -25300 (errSecItemNotFound) and saving returns a status of errSecNotAvailable = -25291.

Save/Load works fine on macOS IF I use:

```
mySQLValet = [[VALValet alloc] initWithSharedAccessGroupIdentifier: @"sharedKeychain"
                                                             accessibility: VALAccessibilityWhenUnlocked];
```

(rather than using VALSynchronizableValet).

So it looks like the issue is probably an iCloud configuration issue with my macOS app.

**Comment by dfed** [comment]
I agree that this seems like an iCloud configuration issue on the macOS app. That said, `errSecNotAvailable` is a weird one. I hate to say this, but have you tried restarting your computer?

**Comment by hankinsoft** [comment]
I was able to sort things out by changing around code signing a bit. All is well now, thank you!
