### ISSUE TITLE
Face ID defaulting?

### ISSUE THREAD

**Issue by stevejcox** [square/Valet#118]
Hi There,

The iPhoneX warns that TouchID is being used and asks the user if they would rather use Face ID. Are there any plans to default to FaceID on the iPhoneX to prevent this message?

Thanks,
Steve

**Comment by NickEntin** [comment]
Good find!  We noticed the same thing and added some documentation to the README (as well as fixing it in the sample app) here: https://github.com/square/Valet/pull/119/files

Hope that helps!  Closing out this issue.

**Comment by stevejcox** [comment]
Thank you, apologies for not noticing the update on the README !

**Comment by dfed** [comment]
Your comment prompted us to update the README (your Issue came first), so thanks for giving us the push!
