### ISSUE TITLE
Use `@available(iOS 9.0, *)`

### ISSUE THREAD

**Issue by yzhong52** [square/Valet#121]
There are a lot of warnings in code around iOS 9.0 availabilities. e.g.:

```
#if ((TARGET_OS_IPHONE && __IPHONE_9_0) || (TARGET_OS_MAC && __MAC_10_11))
    if ([[self class] _iOS9OrLater] || [[self class] _macOSElCapitanOrLater]) {
        baseOptions = @{ (__bridge id)kSecUseAuthenticationUI : (__bridge id)kSecUseAuthenticationUIFail };
    } else {
```

Any plans on fixing those at all? Seems like can fix them easily by wrapping code inside: 

```
if (@available(iOS 9.0, *)) {
    // ... 
}
```

**Comment by dfed** [comment]
Are you seeing build warnings? Or are you objecting to the use of `#if` lines for code flow over the use of `@available?` We explicitly use 
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
...
#pragma GCC diagnostic pop
```
to avoid triggering warnings.

Keep in mind that our current minimum supported Xcode version is 6.3, which doesn't support the `@available` syntax. We'll be rolling our minimum version to Xcode 9 in Valet 3 (check out our progress there in #80), where we'll use `@available`.

**Comment by yzhong52** [comment]
@dfed Thanks for the prompt response! We are seeing build warnings in Xcode 9. That's why I asked. I am not against using `#if`. 

It is amazing to know that Valet supports down to Xcode 6.3. That's real commitments! 😄 👍 

But anyway, that answers my question and it is good to know that Valet 3 is on the way. Looking forward to that!!
