### ISSUE TITLE
Add Concurrency section to README

### ISSUE THREAD

**Issue by dfed** [square/Valet#122]
It'd be great for us to have a section highlighting the work we've done to make Valet instances thread-safe, and to recommend that adoptees don't use Valet objects on the main queue.

Credit to @AndrewSB for [this suggestion]( https://github.com/square/Valet/pull/80#pullrequestreview-95171524)!

**Comment by jshier** [comment]
Barring such a section in the near term, can you outline why we shouldn't use Valet objects from the main queue? Is it just that the access is synchronous and larger amounts of data could block the queue? Also, if asynchronous access is recommended, is Valet interested in an async wrapper?

**Comment by dfed** [comment]
@jshier Keychain items are stored on-disk. So, treat reading and writing Valet objects like you would any other to/from disk serialization/deserialization – think of it as a more secure/advanced version of UserDefaults. I personally advise against accessing the disk (and UserDefaults) on the main queue.

I don't think Valet should have a built-in async wrapper, since I don't want to prescribe to our adoptees how to write async code. The job of Valet is to make the Keychain APIs easy to use, full stop.
