### ISSUE TITLE
support xcode 9

### ISSUE THREAD

**Issue by wjmelements** [square/Valet#141]
Valet uses swift 2 which xcode 9 does not support. After doing pod install with

```rb
    platform :ios, '9.0'
    use_frameworks!
    pod 'Valet'
```

I get 

```
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
```

Swift language version can be specified per-target, so it would make sense to set it for this project.

**Comment by dfed** [comment]
@wjmelements I think you may have a problem with your Pods configuration. Valet 3.0 was a complete rewrite from Objc -> Swift, and we rewrote it in [Swift 4](https://github.com/square/Valet/blob/master/.swift-version).

My guess is you'll get the above error importing any/all Swift projects. I'm closing this out.

If you're looking for a quick workaround that doesn't address the underlying configuration issue, you can try pinning to Valet 2.0, which was written in Objective C.

**Comment by wjmelements** [comment]
Okay, similar to https://github.com/jessesquires/JSQCoreDataKit/issues/98, the work that needs to be done here is to specify the required swift version in the podfile.

> s.pod_target_xcconfig = { 'SWIFT_VERSION' => '4.0' }
