### ISSUE TITLE
How to Detect 3 Failed Touch ID Fingerprints ?

### ISSUE THREAD

**Issue by CaptainScavo** [square/Valet#148]
If I am using VALSecureEnclaveValet, and I call:
```
BOOL cancelled = NO;
[secureValetInstance stringForKey:userPrompt:userCancelled:&cancelled];
```
Is there a way for me to tell whether the user pressed Cancel on Touch Id dialog vs the user entered 3 incorrect fingerprints into the Touch ID dialog ? I get cancelled = YES  for both.

**Comment by dfed** [comment]
We currently do not vend a way to tell the difference between these kinds of events. That said, we're considering add a way per #143. I'm curious to know what use case you're solving for here – please leave a comment on #143.

Since this is a duplicate request, I'm closing this out.
