### ISSUE TITLE
XCTest-watchOS.git does not exist Error 

### ISSUE THREAD

**Issue by elyasns** [square/Valet#155]
On the new release `v3.2.0`, there is an error in Carthage build for watchOS test git repo.

`fatal: repository '../../dfed/XCTest-watchOS.git' does not exist`

**Comment by dfed** [comment]
Oh no. Thanks for the report! I’m guessing that this is because I used a relative git  submodules path. I’ll see if I can fix this later today. My guess is I need to move to using HTTPS.

**Comment by dfed** [comment]
Release 3.2.1 should fix this.
