### ISSUE TITLE
update to Swift 4.2

### ISSUE THREAD

**Issue by andy1247008998** [square/Valet#163]
Would you please update Valet to Swift 4.2?
Thank you!

**Comment by dfed** [comment]
Hi @andy1247008998! Valet should compile just fine with Swift 4.2. If you can answer the following questions, it'll help me understand what we need to better support:
1. What version of Valet are you using?
1. What dependency manager are you using (if any) to integrate Valet into your project?
1. What platform(s) are you using Valet on?
1. What build error or warning, if any, are you seeing?

**Comment by andy1247008998** [comment]
> Hi @andy1247008998! Valet should compile just fine with Swift 4.2. If you can answer the following questions, it'll help me understand what we need to better support:
> 
> 1. What version of Valet are you using?
> 2. What dependency manager are you using (if any) to integrate Valet into your project?
> 3. What platform(s) are you using Valet on?
> 4. What build error or warning, if any, are you seeing?

You are right. It compiles just fine.
<img width="730" alt="2018-11-16 11 18 02" src="https://user-images.githubusercontent.com/7299189/48595840-64794900-e991-11e8-8dea-f7ca8d02067c.png">
I just want to know if we can set its `Swift Language Version` to 4.2.

**Comment by dfed** [comment]
Got it, this is to avoid the "Valet can be updated to 4.2" warning in Xcode?

The problem with setting the compilation flag to 4.2 is that could be a breaking change for:
1. Anyone using submodules to consume Valet. Libraries using 4.0 can't depend on libraries using 4.2.
1. Anyone using Xcode 9, which we still support.

I'd love for Xcode to let us explicitly support both 4.0 and 4.2, but right now we can only support both implicitly 😞

If you're using Cocoapods to consume Valet, and all of your pod dependencies can be compiled on Swift 4.2, you can add the following to the end of your Podfile to get rid of the warning:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Needed until CocoaPods supports multiple Swift versions
      # https://github.com/CocoaPods/CocoaPods/issues/8191
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
```

If you're using another dependency manager, let me know and maybe we can figure out another way to get rid of the warning.

In the meantime, I'm going to close this issue. We have plans to update the Xcode project and Cocoapod config once we release our next breaking change.
