### ISSUE TITLE
Issues building in Xcode 10.2

### ISSUE THREAD

**Issue by JetForMe** [square/Valet#168]
For some reason in Xcode 10.2, I can't use Valet from Objective-C. The Valet.h header is empty except for your comment block. My Cartfile entry is:

```
github "Square/Valet"
```

**Comment by dfed** [comment]
There isn't anything in `Valet.h`, because a this project is written in Swift after version 3. Is there no generated `Valet-Swift.h`? Our Swift classes should be exposed to Objective-C.

**Comment by JetForMe** [comment]
Yes, there is. For whatever reason now, I'm getting errors like

```
MyFile.m:104:17: Receiver 'VALValet' for class message is a forward declaration
```

Even though there's a `#import <Valet/Valet.h>` at the top, and it worked before I updated to Xcode 10.2.

**Comment by dfed** [comment]
Do you have any other Swift libraries you're importing that are working? If there's any chance you could reproduce this in a small sample app, that'd be amazing.

**Comment by JetForMe** [comment]
Yeah, everything else is working (eg Alamofire, PromiseKit, but those aren’t accessed from obj-c). I’ll try to make a sample. 

-- 
Rick Mann
rmann@latencyzero.com

**Comment by JetForMe** [comment]
[TestValetObjC.zip](https://github.com/square/Valet/files/3020150/TestValetObjC.zip)

The attached project exhibits this problem. Uncompress it, run `carthage update --platform ios` in the directory, then try to build it.

**Comment by JetForMe** [comment]
This might be relevant. See the first bullet under "Known Issues": https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes

I thought `-Swift.h` files were generated by Xcode, but this implies the need to do some manual massaging.

**Comment by JetForMe** [comment]
Ah yes, it compiles for device but not simulator.

**Comment by dfed** [comment]
Thank you for the sample project!

> See the first bullet under "Known Issues": https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes

Sounds like this may be a Carthage issue? I'm guessing that if you compile Valet from source it'll compile.

**Comment by JetForMe** [comment]
Valet compiles, even with Carthage. It's just that something isn't generating an appropriate header.

**Comment by JetForMe** [comment]
Ah: https://github.com/Carthage/Carthage/issues/2718
