### ISSUE TITLE
Master Package.swift is not usable in Xcode 11

### ISSUE THREAD

**Issue by jshier** [square/Valet#183]
When trying to use Valet with Xcode 11, the 3.2.5 release doesn't work, so I've tried using `master`. That worked great until the LegacyValet work. Now it errors out when adding to Xcode with the error:

> : package 'valet' is required using a revision-based requirement and it depends on local package 'legacyvalet', which is not supported

So it seems an official tag is necessary or a different solution to whatever the LegacyValet work was fixing.

**Comment by dfed** [comment]
TIL that local packages & published packages don't play nicely together. Thank you for reporting! @jshier I assume https://github.com/square/Valet/commit/0d3fb186e1b235e8c99bead4af5146afb9ca3ca1 works for you, and https://github.com/square/Valet/commit/1d7f401d0075b03a7d31bb7d752f6225372bdcff doesn't? If so, I'll get us back to the working state.

**Comment by jshier** [comment]
Yes, https://github.com/square/Valet/commit/0d3fb186e1b235e8c99bead4af5146afb9ca3ca1 works, https://github.com/square/Valet/commit/1d7f401d0075b03a7d31bb7d752f6225372bdcff does not.

**Comment by dfed** [comment]
Release 3.2.6 should work for you now
