### ISSUE TITLE
I can run my swift project  on my iPhone , but this error is shown all the time .

### ISSUE THREAD

**Issue by FallacyWalker** [square/Valet#188]
![Screen Shot 2019-10-26 at 16 13 42](https://user-images.githubusercontent.com/20806018/67616499-2bd22880-f80c-11e9-8b87-a0ea380dd8c2.png)

**Comment by dfed** [comment]
If I’m going to be able to help or diagnose the issue I’m going to need way more information.

How are you integrating Valet into your project? Are you using Swift packages? Cocoapods? Carthage? Manual Xcode integration? Something else? Also: what version of Xcode are you running? What version of iOS is your iPhone running?

It looks like you also have Alamofire in your project, and it doesn’t seem like Alamofire has the same issue. Are you integrating that project the same way you are integrating Valet?

Attaching a build log could also be helpful if you don’t mind sharing.

**Comment by dfed** [comment]
Closing this issue. I have insufficient information to address it.
