### ISSUE TITLE
Friendlier NS_ENUM names?

### ISSUE THREAD

**Issue by stephencelis** [square/Valet#2]
This might be a **wont fix**, but `VALAccessibility` and `VALMigrationError`, _e.g._, don't follow the standard of prefixing all enum values with the enum type itself.

That is, rather than `VALAccessibleWhenUnlocked`, it would be `VALAccessibilityWhenUnlocked`.

I can understand that the former is more readable when typed out, but it breaks the Cocoa convention and creates slightly more verbose Swift code.

**Comment by dfed** [comment]
Good point! Renaming `VALAccessibility` to `VALAccessible` seems reasonable, and keeps the legibility. `VALMigrationError` is an easy change.

Will play with it and get back to you :)

**Comment by dfed** [comment]
After toying around I went with your original suggestion: https://github.com/square/Valet/pull/3

**Comment by dfed** [comment]
We've got a PR to address this, so I'm closing this issue.
