### ISSUE TITLE
Support sharing keychain items using App Groups

### ISSUE THREAD

**Issue by dfed** [square/Valet#222]
Currently, we only support sharing keychain items with Keychain Access Groups.

We should also support keychain sharing via App Groups.

More information on the differences between Keychain Access Groups and App Groups can be found in Apple's [documentation](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps).

**Comment by dfed** [comment]
Worth noting that [the format of App Group IDs differ on macOS and other platforms](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_application-groups#discussion).

**Comment by dfed** [comment]
According to [the documentation on `kSecAttrAccessGroup`](https://developer.apple.com/documentation/security/ksecattraccessgroup), it seems that App Group sharing uses the `kSecAttrAccessGroup` key. Which means that we may have enabled unofficial support for App Groups in #218 when we enabled explicitly setting the access group prefix. If I'm right, supporting this feature may be as simple as updating the docs and tests. Investigating.

**Comment by dfed** [comment]
An initial investigation reveals that we are indeed supporting this functionality today! I'm working on a PR to update some names to make the support a bit more semantic. PR incoming. We'll want to land this in Valet 4 (or roll a Valet 5 fast-follow, which seems less-than-ideal).

**Comment by NickEntin** [comment]
Awesome! Landing in Valet 4 sounds good. 👍

**Comment by dfed** [comment]
This will be released in Valet 4. Closing this issue.
