### ISSUE TITLE
Why cant u make a library thats simple and just works? 

### ISSUE THREAD

**Issue by fresh83** [square/Valet#23]
http://postimg.org/image/bkohss797/219385d9/

**Comment by dfed** [comment]
Looks like you're using an older version of Xcode. Until you update Xcode use Valet release 1.2.1. 1.3 requires Xcode 6.3 or later. Minimum Xcode version requirement documentation is coming shortly. Sorry about that!

**Comment by dfed** [comment]
Closing this issue as I believe it is resolved. @fresh83 please let us know if downgrading to Valet 1.2.1 or upgrading your Xcode version doesn't fix this.
