### ISSUE TITLE
Add renamed annotations to Valet 4 release to ease migration

### ISSUE THREAD

**Issue by idrougge** [square/Valet#238]
The latest release on the Github page is 3.2.8, whereas the latest Cocoapod is 4.1.0.

4.1.0 also lacks `@deprecated` or `renamed` annotations, making migration difficult.

**Comment by dfed** [comment]
Thank you for the reminder to fill out the Releases page on GitHub! I’ll do that today. Yes, 4.0 and 4.1 should be released. In the meantime, #179 has a list of improvements in 4.0.

I can also explore adding `renamed` annotations in later this week.

**Comment by dfed** [comment]
I've updated the Releases page. I'm going to re-task this Issue to ask for `renamed` annotations.
