### ISSUE TITLE
Migrating from Valet 3 to 4 causing to data loss issue

### ISSUE THREAD

**Issue by Suri1044** [square/Valet#240]
Hi Team, I am using Valet 3.2.8 and Migrated to latest Valet 4.1.1.
Problem: After migration, its not detecting or reading the touch id.
Query:
The class method used to create a Valet that can share secrets between applications using keychain shared access groups has changed. is it causing the issue ? as group is introduced ?

That means all my existing users new to login again first to use touchid with this new migration of Valet 4.1.1 ? Please confirm.

**Comment by dfed** [comment]
Thanks for the report @Suri1044! This shouldn't be happening. Can you give us some more info so we can investigate?

1. What platform you are using Valet on? I.e macOS, iOS, watchOS, tvOS, or some combination.
1. What class you're using to read items from the keychain.
1. Which method you're using to retrieve your Valet instance.
1. What error you're getting when you read from the keychain after update. I.e `itemNotFound`, or something else?

If you can include the code you use to construct and read values from a Valet before and after updating, that'd be ideal. We have integration tests that should prevent this kind of regression, so sharing a snippet of your source will help us understand what might have gone wrong.

**Comment by Suri1044** [comment]
@dfed : Please find my inline comments below.

1. What platform you are using Valet on? I.e macOS, iOS, watchOS, tvOS, or some combination.
Comment: iOS

2. What class you're using to read items from the keychain.
Comment: secureEnclaveValet.string(forKey:withPrompt:)

3. Which method you're using to retrieve your Valet instance.
Comment: SecureEnclaveValet.sharedGroupValet

Valet.sharedGroupValet(with: SharedGroupIdentifier(groupPrefix: "group", nonEmptyGroup: "mygroupid")!, accessibility: .whenUnlockedThisDeviceOnly)

Query: With new "group" syntax added, will it consider as new instance ? (exiting method data is not reused). 

4. What error you're getting when you read from the keychain after update. I.e itemNotFound, or something else?
Comment: I didn't get any error but saved username and password are not there, because of this i need to enter credentials again after this migration. Existing users will have an effect (need to enter again) if i release this migration valet.

**And need one more help.** 
secureEnclaveValet.string(forKey: "password", withPrompt: "Enter password") which used to return SecureEnclave.Result<String>. Now its returning String only.
With Result string i used switch case to determine success or other cases as below in app.
How to achieve the same with these new return string. Good if we have proper document/code for this.

Old code with SecureEnclave.Result<String>

switch SecureEnclaveManager.shared.password {
        case .success(let password):
            //  Login the user
        case .userCancelled:
           // user cancelled
        case .itemNotFound:
          // itemnotfound
        }

Need same code for new string return
Appreciate for your quick response.

**Comment by dfed** [comment]
@Suri1044 I believe you're using the wrong `SharedGroupIdentifier` initializer. Support for App Groups (which is what is enabled when you use `SharedGroupIdentifier(group:nonEmptyGroup:)` were introduced in Valet 4 – this feature wasn't supported in Valet 3. What you want is `SharedGroupIdentifier(appIDPrefix:nonEmptyGroup:)`, which uses Shared Access Groups to share items, which is what was supported in Valet 3. I'll see if I can make this more clear in the README's "Migrating from Valet 3" section.

Regarding error handling in Valet 4, the `string(forKey:withPrompt:)` method [`throws` a `KeychainError` when it fails](https://github.com/square/Valet/blob/c9e7a1e5e0cb73f07cafb403c53c4922e22e5357/Sources/Valet/Valet.swift#L304). You can read up on Apple's documentation for [error handling in Swift](https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html) to learn more about how to use `throws`. The [`KeychainError` type](https://github.com/square/Valet/blob/c9e7a1e5e0cb73f07cafb403c53c4922e22e5357/Sources/Valet/KeychainError.swift#L25) actually enumerates more possible failures than you had access to in Valet 3.
