### ISSUE TITLE
Free YouTube video on how to use Valet on iOS

### ISSUE THREAD

**Issue by rebeloper** [square/Valet#249]
Hi,❤️ Valet and using it in some of my client apps already. So I decided to create a hands on video tutorial on why Valet is so straightforward to use. Take a look at it here: https://www.youtube.com/watch?v=E2Z8BBARlvs&list=PL_csAAO9PQ8Z9QxzfRxpN1YrVHXmncTSU&index=3
Hope you will love watching it as much as I liked working with Valet.
If you did like it consider adding it to the README file so others may discover Valet through a video. You may use this image if you wish (images are more likely to be clicked :) )
![Keychain](https://user-images.githubusercontent.com/2488011/96146620-2aaf7500-0f0f-11eb-9ef6-1340f1a7d0cf.png)

Let me know your thoughts on the video. Any feedback will help.
Thanks for the great repo,
Alex

**Comment by dfed** [comment]
Hi @rebeloper!

I absolutely love this enthusiasm. Thank you so much for making this video. Apologies for taking so long to get back to you – I wanted to make sure I had watched your whole video before responding.

A couple nits:
* 3:40: You mention that the Valet identifier is for "that key only", which makes it sound like there's a 1:1 mapping between identifiers and keys. What an identifier does is create a named sandbox in the keychain where multiple keys and values can live. A Valet with one identifier can't read from a Valet with a different identifier.
* 13:35: It sounds like you're saying that the identifier has to be the same when migrating between different valets. That isn't true! You can migrate between any two valets that support migration.

Let me know when you've updated the above and I'll throw a link into the README. I appreciate your working to make Valet more approachable to folk who prefer to watch videos over reading READMEs.

**Comment by rebeloper** [comment]
Hey, thanks for getting back. While I cannot re-record the video I have added your observations first thing in the description. Hopefully that will be enough for the video to make it in the README.
