### ISSUE TITLE
Module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by exofthalmus** [square/Valet#252]
Hi!
Since updating to the newest X-Code IDE i'm getting the following error:

/Users/flosse/Projekte/ent/SpesenApp/SpesenApp/SpesenApp/Core/RestRequestServiceInterceptor.swift:11:8: Module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler: /Users/flosse/Projekte/ent/SpesenApp/SpesenApp/Carthage/Build/iOS/Valet.framework/Modules/Valet.swiftmodule/arm64-apple-ios.swiftmodule

Tried a few things but nothing worked. What ca i do? I'm using carthage with following command:
github "Square/Valet"

Thx and greetings Chris

**Comment by dfed** [comment]
@exofthalmus this looks like an issue with Carthage, based on [their documentation](https://github.com/Carthage/Carthage#swift-binary-framework-download-compatibility):
> Carthage will check to make sure that downloaded Swift (and mixed Objective-C/Swift) frameworks were built with the same version of Swift that is in use locally. If there is a version mismatch, Carthage will proceed to build the framework from source. If the framework cannot be built from source, Carthage will fail.

It looks like Carthage should be building Valet from source rather than straight failing. I don't know enough about Carthage's Swift support to be able to assist you further. Consider filing an issue with Carthage after trying their [troubleshooting steps](https://github.com/Carthage/Carthage#resolve-build-failures)?

**Comment by exofthalmus** [comment]
Hin Dan!

Ah ok, i thought it has something to do with the Valet-Framework.

So i’m sorry to waste your time and i will look what else could be wrong.

Ich already updatet everything.

Best regards
Christian

Von: Dan Federman <notifications@github.com>
Gesendet: Dienstag, 10. November 2020 16:34
An: square/Valet <Valet@noreply.github.com>
Cc: FLASSER Christian <christian.flasser@bat.at>; Mention <mention@noreply.github.com>
Betreff: Re: [square/Valet] Module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler (#252)


@exofthalmus<https://github.com/exofthalmus> this looks like an issue with Carthage, based on their documentation<https://github.com/Carthage/Carthage#swift-binary-framework-download-compatibility>:

Carthage will check to make sure that downloaded Swift (and mixed Objective-C/Swift) frameworks were built with the same version of Swift that is in use locally. If there is a version mismatch, Carthage will proceed to build the framework from source. If the framework cannot be built from source, Carthage will fail.

It looks like Carthage should be building Valet from source rather than straight failing. I don't know enough about Carthage's Swift support to be able to assist you further. Consider filing an issue with Carthage after trying their troubleshooting steps<https://github.com/Carthage/Carthage#resolve-build-failures>?

**Comment by dfed** [comment]
No worries! Dependency managers are hard – I've certainly struggled with them myself. Good luck!
