### ISSUE TITLE
Feature Request, Unlock with Apple Watch

### ISSUE THREAD

**Issue by plananderson** [square/Valet#253]
```swift
@available(macCatalyst 13.0, *)
@available(iOS, unavailable)
public static var watch: SecAccessControlCreateFlags { get }
```

more info [here](https://developer.apple.com/documentation/security/secaccesscontrolcreateflags/3042482-watch)

**Comment by dfed** [comment]
Interesting! We could certainly add enum options that include `watch` to `SecureEnclaveAccessControl`.

I don't think there's much of a case for a watch-only unlock. So maybe we add the following cases:
```
case userPresenceOrWatch
case biometricAnyOrWatch
case biometricCurrentSetOrWatch
case devicePasscodeOrWatch
```

@NickEntin, thoughts?

**Comment by NickEntin** [comment]
Agreed this would be good to add and I think that sounds like a reasonable approach. I suspect watch-only is a fairly uncommon configuration, so it's probably reasonable to leave that out for now until/unless we have a clear use case.

At a higher level, this enum could get pretty verbose pretty fast when another access method is added. This might be better represented by something like:

```swift
struct SecureEnclaveAccessControl {

    var acceptDevicePasscode: Bool

    enum BiometricVerificationAcceptance {
        case any
        case currentSet
        case none
    }

    var acceptBiometricVerification: BiometricVerificationAcceptance

    var acceptWatch: Bool

}
```

Of course, that would be a breaking change, so not something we'd want to do right now.

**Comment by dfed** [comment]
Agreed that a struct or option set would make for a better long-term option. In the spirit of shipping a feature bump rather than a breaking change though, I may take this approach and file a wishlist item for the next major bump.

**Comment by dfed** [comment]
So I did some investigation on my Mac Mini, and it seems that (despite Apple's documentation) `.userPresence` already allows access via watch or passcode:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/139364/107982354-ba763600-6f78-11eb-806b-bcf1125ec2b3.png">

Furthermore, when storing a secret with `SecAccessControlCreateFlags(rawValue: SecAccessControlCreateFlags.devicePasscode.rawValue | SecAccessControlCreateFlags.watch.rawValue)` actually requires customers to unlock the secret by authenticating with **both** the passcode and the watch, sequentially.

Additionally, storing a secret with `SecAccessControlCreateFlags(rawValue: SecAccessControlCreateFlags.biometricAny.rawValue | SecAccessControlCreateFlags.watch.rawValue)` straight fails with `userCancelled` if there is no biometric sensor on the device.

Given the above, I think we can waive off of any logic changes on this issue and instead just update our documentation.

**Comment by plananderson** [comment]
Thanks!

**Comment by dfed** [comment]
> Additionally, storing a secret with `SecAccessControlCreateFlags(rawValue: SecAccessControlCreateFlags.biometricAny.rawValue | SecAccessControlCreateFlags.watch.rawValue)` straight fails with `userCancelled` if there is no biometric sensor on the device.

I'm realizing this test likely should have been `SecAccessControlCreateFlags(rawValue: SecAccessControlCreateFlags.biometricAny.rawValue | SecAccessControlCreateFlags.or.rawValue | SecAccessControlCreateFlags.watch.rawValue)` to get the "or" semantics right. I'll test this when I'm back near my M1 machine.
