### ISSUE TITLE
Add convenience access methods for `Codable` types

### ISSUE THREAD

**Issue by Jeehut** [square/Valet#254]
As of now, we have basically two methods for accessing data, namely `string` (`string(forKey:)`, `setString(:forKey:)`) and `object` (`object(forKey:)`, `setObject(:forKey:)`). While this covers all use cases as users can convert any type to `Data` and store it via `object` to the keychain, it's quite inconvenient to write the conversion code each time. Especially now that Swift has an official way of specifying that types can be made `Codable` to communicate to others (incl. this library) that there's a uniform way of archiving and unarchiving the type.

So what I suggest is that we add convenience methods to this great library which automate the conversion to and from `Data` for all `Codable` types. To simplify the code here in the library, we probably shouldn't take any responsibility of reacting to conversion errors, instead we should just rethrow them and let the users handle any issues with encoding/decoding. For that I think it's important that we also document as part of the new APIs which encoder/decoder we're using so that users of this library can transparently handle the possible errors.

**Comment by dfed** [comment]
I like this idea a lot! Thank you for the suggestion. I particularly like that Valet wouldn't take responsibility for error handling during the encoding/decoding process.

Taking the concept of reducing Valet's responsibility a step further: how would you feel about Valet allowing consuming code to specify which encoder or decoder should be used? I think this could take the form of a parameter on the new methods for retrieving and storing `Codable` objects. We could also have a default argument in case the consuming code doesn't have strong opinions about which encoder or decoder to use.

I'm hoping we can keep this API a thin layer on top of Apple's `Codable` functionality without having to later add support for alternative encoders or decoders. The only subject `Valet` should be opinionated about is how to use the Keychain. Everything else should be up to the consumer 🙂

**Comment by Jeehut** [comment]
@dfed Thank you, great to hear that you like the idea. I also like yours, let me adjust my PR to reflect what you suggested...

**Comment by Jeehut** [comment]
@dfed I just tried passing the encoder as a parameter so you could use any encoder, but I don't think it's a good idea for the following reasons:

1. My first approach was to specify a new `encoder: Encoder = JSONEncoder()` parameter, but it appears that `JSONEncoder` doesn't even conform to `Encoder`, see the following screenshot:
![Encoder](https://user-images.githubusercontent.com/6942160/107683082-7269c180-6ca1-11eb-9777-8b649149aff6.png)

2. Next, I checked what `JSONEncoder` and `PropertyListEncoder` conform to and found the `encode()` method is required by the `TopLevelEncoder` protocol which is part of Combine. Combine, as you probably know requires iOS 13 as its minimum version. So I'm not sure if it's a good idea to restrict this new API to only iOS 13+ ... what do you think?
![TopLevelEncoder](https://user-images.githubusercontent.com/6942160/107683358-c07ec500-6ca1-11eb-9ed5-5382950480df.png)

I would suggest that we instead provide a `jsonEncoder: JSONEncoder = JSONEncoder()` parameter. This way at least users would be able to provide a custom `JSONEncoder` object with their preferred encoding/decoding strategies. Looking forward to your inputs here, I'm quite undecided.

**Comment by Jeehut** [comment]
I just adjusted my PR with my suggestion, feel free to check.

**Comment by dfed** [comment]
Sorry for the delay @Jeehut. I don't mind restricting the new convenience API to iOS 13+ since this functionality isn't critical to the library working.

If we wanted to make the API compatible with older iOS versions, we could create our own `ValetEncoder` and `ValetDecoder` protocols that look similar to [this encoder](https://github.com/dfed/CacheAdvance/blob/364d4d2cc31bb0cd5ef30ac01104b6b989704c47/Sources/CacheAdvance/MessageEncoder.swift#L20) and [this decoder](https://github.com/dfed/CacheAdvance/blob/364d4d2cc31bb0cd5ef30ac01104b6b989704c47/Sources/CacheAdvance/MessageDecoder.swift#L20). Having our own encoder/decoder protocols feels a little clunky though, especially when there is a protocol already available in Combine. Open to arguments either way.

I'll take a look at the PR.

**Comment by dfed** [comment]
I'm going to close this request out. I do like the thinking behind it, but given that we haven't seen folk clamoring for this additional API and the complexities we ran into on #255, I'm not sure this API is worth the effort. It is quite simple for consuming applications to write their own Codable APIs that wrap Valet via an extension, so at a minimum we're not preventing someone from writing this API themselves.
