### ISSUE TITLE
.whenUnlocked vs .afterFirstUnlock

### ISSUE THREAD

**Issue by sergstav** [square/Valet#257]
Maybe a simple question, by I really struggle with it. Can you please explain what the difference between these types of accessibility.

.whenUnlocked says that
Valet data can only be accessed while the device is unlocked.

and .afterFirstUnlock says that
Valet data can only be accessed once the device has been unlocked after a restart.
What really means that 'once'? Data can only be accessed once really once? Seem it available every time I launch an app.

Or I understand correctly .afterFirstUnlock means that if I turn on my phone but not unlocked Keychain will not return data? So, to get data I have to unlock device + this type allows to use data in backgroud.

Thank you.

**Comment by sethfri** [comment]
Hi @sergstav, the word "once" here is used as a conjunction, meaning "as soon as" or "when". It does not mean "one time only" in this case.

> Or I understand correctly .afterFirstUnlock means that if I turn on my phone but not unlocked Keychain will not return data? So, to get data I have to unlock device + this type allows to use data in backgroud.

This is correct. If you restart your phone and do not unlock it, the keychain will not return data in this case.

Hope that's helpful!

**Comment by dfed** [comment]
Thanks for asking the question! I'll take this as an opportunity to update the language to make it more clear.

`whenUnlocked` means that the data is accessible whenever the device is unlocked.

`afterFirstUnlock` means that the data is accessible after the device has been unlocked a single time after a reboot. This means that the data is:
1. Accesible when unlocked
1. Accessible when the device is locked,  but only after the device has been unlocked at least one time after a reboot.
