### ISSUE TITLE
SecKeychainAddCallback(_:_:_:) along with Valet 

### ISSUE THREAD

**Issue by vamsig7** [square/Valet#264]
Is it possible to add ``` SecKeychainAddCallback(_:_:_:) ``` and get a callBack when KeyChain  items modified  ?

I tried implementing it and looks like callbacks are not consistent ,some of them  are missing . I am getting callbacks for keychain lock and unlock events but have issues for writing /deleting keychain items .Does it have something to do with internal logic of Valet  

Please let me know if I can provide any more details
MacOS 10.15
Xcode 12+
Link to  documentation 
https://developer.apple.com/documentation/security/1394998-seckeychainaddcallback

Thank You

**Comment by vamsig7** [comment]
Thanx for quick response   as always 😍
I tried commenting each line  and I guess the issue is with  
 ``` baseQuery[kSecUseDataProtectionKeychain as String] = true ```  
line no: 64 in  Valet/Sources/Valet/Internal/Service.swift , when I toggled it to false ,everything works as expected  and  callbacks are accurate 

[kSecUseDataProtectionKeychain](https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain) .
Rather than issues with portability, does this  attribute fix any security implications (or) What's the disadvantage of removing this flag?


Thank You

**Comment by dfed** [comment]
Good sleuthing! It seems like the callback API only works the older implementation of the macOS keychain – that's unfortunate 😞

The reason for this key is outlined in https://github.com/square/Valet/issues/213#issuecomment-578420851: this key is required for utilizing the [kSecAttrAccessGroup](https://developer.apple.com/documentation/security/ksecattraccessgroup) and [kSecAttrAccessible](https://developer.apple.com/documentation/security/ksecattraccessible) fields, both of which we rely on for core functionality. I believe removing this key would result a bunch of unexpected behavior from Valet – accessibility fields would be ignored, and Valets with different identifiers would be able to read and write one another's values.

**Comment by brettstover** [comment]
@dfed @vamsig7 Just wanted to let you know I found a workaround to this issue and posted about it here: https://developer.apple.com/forums/thread/88888

> I encountered this same issue today: callback function never fires if SecItemCopyMatching has been called, but fires fine if SecItemCopyMatching hasn't been called. I had success by removing the callback before calls to SecItemCopyMatching and then adding it back afterwards. Odd, but as far as workarounds go it's not the worst. Weirdly, it must be: remove callback, SecItemCopyMatching call, add back callback; SecItemCopyMatching call, remove callback, add back callback doesn't seem to work.
