### ISSUE TITLE
Keychain Sharing between iOS App and Apple Watch Extension

### ISSUE THREAD

**Issue by kschins** [square/Valet#275]
I am initializing my `Valet` as such:

`let sharedGroupIdentifier = SharedGroupIdentifier(appIDPrefix: "XXXXXXXXXX", nonEmptyGroup: "com.tppy.tppy.SharedKeychainGroup")!`

`valet = Valet.sharedGroupValet(with: sharedGroupIdentifier, accessibility: .afterFirstUnlock)`

This is initialized in a shared class used by the iOS app as well as the Watch app. I am using my Team ID in place of the `XXXXXXXXXX` mentioned above. In my entitlement file for the iOS app, I have `$(AppIdentifierPrefix)com.tppy.tppy.SharedKeychainGroup` and the same is in my Apple Watch entitlement file. Lastly, when I added the capability to each target, the keychain group is defined as `com.tppy.tppy.SharedKeychainGroup`.

Is there something I am missing because currently I am unable to share any keychain items between the two apps?

**Comment by dfed** [comment]
Can you define "unable to share any keychain items between the two apps"? Can both apps read from the the instantiated `valet` or are you getting errors thrown? If you're seeing errors, what are the errors?

**Comment by kschins** [comment]
I am not getting any errors. What I meant is that values saved to the keychain in the iOS app are not being retrieved or are not accessible by the Apple Watch app. I want to share a few tokens between the two apps so I can properly display authenticated/unauthenticated data on the watch app. My understanding is that using keychain access groups allows both apps to initialize a valet with the same group and read/write from that valet.

**Comment by dfed** [comment]
> I am not getting any errors.

Given that our retrieval API `throws` when there's no item found, I don't think this is strictly true. You're saying that the Apple Watch app is reading from the `valet` is getting [the `itemNotFound` error](https://github.com/square/Valet/blob/bce7b399f3c2a6e0c444aa3b12b5b1fb1ee48c71/Sources/Valet/KeychainError.swift#L27) thrown?

> My understanding is that using keychain access groups allows both apps to initialize a valet with the same group and read/write from that valet.

This understanding is correct. I currently deploy apps that do this.

**Comment by kschins** [comment]
Yes, I am getting `itemNotFound` thrown when trying to retrieve values from the `valet` within the Apple Watch app.

**Comment by dfed** [comment]
🤔. So I know that a `.sharedGroupValet` works for sharing data between a host app and embedded extensions, but watch extensions are no longer embedded and instead run separately on the watch. Per [this developer help thread](https://developer.apple.com/forums/thread/79866) it seems like the move to make the watch app run on a separate device means that keychain sharing now requires syncing via iCloud. So you'd need a `.iCloudSharedGroupValet` rather than a `. sharedGroupValet`. Let me know if that helps!

**Comment by kschins** [comment]
Makes sense. Thanks for the help, @dfed. I'll attempt another method and close this ticket.
