### ISSUE TITLE
No way to invalidate()

### ISSUE THREAD

**Issue by c128128** [square/Valet#304]
Hi there,

At the moment when using this [`object(forKey key: String, withPrompt userPrompt: String)`](https://github.com/square/Valet/blob/master/Sources/Valet/SecureEnclaveValet.swift#L137), there is no way to `invalidate()` the request.

Something like this might work:
```swift
@objc
public func object(forKey key: String, withPrompt userPrompt: String, context: LAContext) throws -> Data {
    try execute(in: lock) {
        var keychainQuery = baseKeychainQuery
        keychainQuery[kSecUseAuthenticationContext as String] = context
        
        return try SecureEnclave.object(forKey: key, withPrompt: userPrompt, options: keychainQuery)
    }
}
```

Then we can use it like this:
```swift
let context = LAContext()

let se = SecureEnclaveValet.valet(with: Identifier(nonEmpty: Biometry.SERVICE)!, accessControl: .biometricCurrentSet)

se.object(forKey: Biometry.KEY, withPrompt: "", context: context)

context.invalidate()
```

I know this variant is not a perfect fit for current API.

**Comment by dfed** [comment]
I believe you want the `SinglePromptSecureEnclaveValet`, which has the [requirePromptOnNextAccess](https://github.com/square/Valet/blob/c095ce0ac15716bee167aefc273e17c2c3cd4919/Sources/Valet/SinglePromptSecureEnclaveValet.swift#L184) API which calls `invalidate()` under the hood.

I'm closing this issue, but if I misunderstood your use case please feel free to reopen!
