### ISSUE TITLE
Migration from Valet 3 format

### ISSUE THREAD

**Issue by elitree** [square/Valet#307]
Hi! I've got a migrations question, kind of a newbie one. We've been using Valet 3 in our codebase, and need to update to Valet 4. I've reviewed [the documentation on migrating to valet 4](https://github.com/square/Valet?tab=readme-ov-file#migrating-from-valet-3), and am not entirely sure how to proceed. I'm guessing this would make better sense if I really understood how Keychain works.

Previously, we accessed our Valet with: 

```
let valet = Valet.valet(with: Identifier(nonEmpty: "LandGlide")!, accessibility: .always)
```

The documentation says to use the `migrateObjectsFromAlwaysAccessibleValet` for legacy valets like this one, so you could do something like:

```
let newValet = oldValet.migrateObjectsFromAlwaysAccessibleValet(removeOnCompletion: true)
```

My question is, from the line above, how do I define `oldValet`, now that I can't specify the accessibility value of `.always` like I did previously? Again, sorry if this is an obvious one, but I can't tell just based on the documentation. Thanks

**Comment by dfed** [comment]
Hi @elitree! No worries at all.

The documentation states (emphasis added):
> To migrate values stored with always accessibility, use the method `migrateObjectsFromAlwaysAccessibleValet(removeOnCompletion:`) on a Valet **with your new preferred accessibility**

So this would look like:
```
// Replace the newValet configuration with your own configuration:
let newValet = Valet.valet(with: Identifier(nonEmpty: "Druidia")!, accessibility: .afterFirstUnlock)
// Migrate the objects into your new valet:
newValet.migrateObjectsFromAlwaysAccessibleValet(removeOnCompletion: true)
```

Let me know if that makes sense! Also, if you have any suggestions to wording to make the README more clear I'd love to hear them.

**Comment by elitree** [comment]
Thank you for the quick and clear response! This makes more sense to me now. 

Regarding the README, I made some assumptions about what was needed for this migration based on earlier migration examples, in this section: https://github.com/square/Valet?tab=readme-ov-file#changing-an-accessibility-value-after-persisting-data . The example there shows how to explicitly set up an old and a new valet configuration, and then migrate objects from the old configuration to the new one. Based on that example, I was thinking that I'd need to do the same thing for the `migrateObjectsFromAlwaysAccessibleValet ` function since the accessibility was different on the old one. If I'd thought about it just a little more, I'd have realized that the function knows the accessibilty on the old was .always, since that's the point of the function. 

And of course, the function signature is different. I also see that there are several other migration functions which don't expect an old valet as an argument. 

So I can't really think of a good way to change the README in a way that would clarify this for someone like me. Let's chalk it up to Friday fatigue? :)

Thanks again!

**Comment by dfed** [comment]
Sounds like a code example in the migration instructions could go a long way. Thanks for surfacing this issue and for the kind words!
