### ISSUE TITLE
License missing copyright

### ISSUE THREAD

**Issue by fraune** [square/Valet#331]
Hello! Thanks for your work on this library.

Here's an opportunity to update the oldest and least updated file in the repo!

I wanted to properly credit Valet in my app's open source attributions section. When looking though your license file, I saw this:

```
Copyright [yyyy] [name of copyright owner]
```

https://github.com/square/Valet/blob/main/LICENSE#L190

Presumably, it should state something like `Copyright 2015 Square, Inc.`. I'll assume this copyright until someone tells me different, or you update the license.

Cheers!
Brandon

**Comment by dfed** [comment]
An original sin! Thanks for flagging. Will take care of it

**Comment by fraune** [comment]
Haha no problem. Thanks for the quick response :)
