### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by Visorox** [square/Valet#35]
So as some of you may know [Carthage](https://github.com/Carthage/Carthage) is becoming a popular tool for handling dependencies. Carthage is currently iOS 8+ exclusive due to it using frameworks.

What are your thoughts on supporting this?

My basic understanding of how this would work is by duplicating the current static library targets.

**Comment by dfed** [comment]
If supporting Carthage does not affect Cocoapods consumers (or consumers who are still targeting iOS 7), I see no harm in supporting it.

Is there any kind of changes we should make to our CI to support Carthage (or prevent breaking Carthage), in addition to the target changes?

**Comment by dfed** [comment]
Once #42 is in I want to add a Carthage gem to the README

**Comment by dfed** [comment]
@Visorox @eliperkins @dcaunt I've uploaded the Carthage binary to Github. Let me know if it works!

**Comment by eliperkins** [comment]
![screen shot 2015-09-16 at 6 36 59 pm](https://cloud.githubusercontent.com/assets/1051453/9920433/02aced64-5ca2-11e5-9b08-2b5c63716479.png)

https://github.com/eliperkins/ValetExample/commit/e2e4b8d3f01a4f4d33913866e9d691a40efe8214

Works for me! Great job, y'all!

**Comment by dcaunt** [comment]
Looks good to me! 

By the way, if you give your Releases a name (e.g. '2.0.2' rather than using the latest commit message, you'll get more useful output from Carthage. This can be helpful when you've specified a flexible version.

**Comment by dfed** [comment]
@dcaunt didn't realize Carthage didn't version based on git tags. Thanks for raising! This should now be fixed.
