### ISSUE TITLE
Is standard VALValet backed up to iCloud?

### ISSUE THREAD

**Issue by bjarkehs** [square/Valet#38]
Hi,

I'm currently working on a project, where I need to store some strings securely, but they cannot be backed up to iCloud. I know the synchronizable valet works across devices, but I couldn't find anywhere in the README about whether the valet is actually backed up to iCloud. So my question is basically as the subject: Is the standard VALValet backed up to iCloud?

**Comment by dfed** [comment]
Take a look at [VALValet.h](https://github.com/square/Valet/blob/master/Valet/VALValet.h)'s declaration of `VALAccessibility`. Each `VALAccessibility` value is documented as to whether it backs up to iCloud. Given that you don't want the keychain backed up to iCloud, you'll want to choose a `VALAccessibility` that ends in `ThisDeviceOnly`. That said, I recommend reading the full documentation in the header.
