### ISSUE TITLE
Reason for setObject to be NSData?

### ISSUE THREAD

**Issue by bjarkehs** [square/Valet#39]
Is there a specific reason why setObject only takes NSData?

**Comment by dfed** [comment]
NSData is how the keychain stores data (see Apple's documentation of `kSecValueData`). Moreover, conforming to`NSCoding` is pretty much a requirement for storing any object outside of CoreData.

We've written `setString:forKey:` and `stringForKey:` helper methods that make it easy to store passwords and other string values. Out of curiosity, what kind of values are you storing in the keychain?

**Comment by bjarkehs** [comment]
That makes perfect sense. Thanks for taking your time to explain it. I'm storing a string and also an array of strings. So it's not really a problem to make it into ``NSData``

**Comment by dfed** [comment]
Awesome. Closing this out.
