### ISSUE TITLE
removeObjectForKey:options: returns YES when it fails with -34018

### ISSUE THREAD

**Issue by Autoc0diq** [square/Valet#52]
I have been chasing an issue when even after I log out successfully, it logs me back in the next time.
(Disclaimer this is with Xcode debugger attached)

- call removeObjectForKey which returns YES, even though VALAtomicSecItemDelete returned -34018
- immediately call object:forKey to check which as expected returns nil, even though VALAtomicSecItemCopyMatching returned -34018
=> I am assuming that the sequence properly removed the key. However it did not. 

So how am I supposed to call canAccessKeychain() after each call to make sure that they actually succeeded?

**Comment by Autoc0diq** [comment]
It appears to work fine without Xcode debugger attached.

**Comment by dfed** [comment]
That's the error for missing entitlements. So it makes sense that getting onto a signed build would fix it.

But it does seem wrong that `removeObjectForKey:` is returning YES when it failed. Re-opening so I can investigate in the morning.

**Comment by Autoc0diq** [comment]
Actually it's the same build, just running it on device without Xcode attached.

**Comment by dfed** [comment]
Yeah it's only checking `errSecInteractionNotAllowed` and not missing entitlements. I'll need to add that to the checks in the morning

**Comment by Autoc0diq** [comment]
Hard to unit test that one ;-)

**Comment by dfed** [comment]
Weird! In any case, the fix is the same :)

**Comment by dfed** [comment]
This issue has been fixed and is consumable in 2.0.4!
