### ISSUE TITLE
dSYM not included in Framework zip

### ISSUE THREAD

**Issue by tomtaylor** [square/Valet#58]
I noticed that the dSYM is not included in the framework zip that Carthage downloads. We like to include those in the Build Products folder, so we get full backtraces. Is it possible to include it?

**Comment by dfed** [comment]
It does seem possible. Carthage's [README](https://github.com/Carthage/Carthage#copying-debug-symbols-for-debugging-and-crash-reporting) explains how.

I can get to this in a couple weeks, but if you'd like to add this functionality before I get there feel free. FWIW, I have never seen Valet crash in the wild (hopefully you haven't either!)

**Comment by tomtaylor** [comment]
Thanks @dfed, we haven't either! It just caught us out, because if we build from scratch it includes the dSYM, and copying it over is one of our build phases. Happy to give you a new zip to replace the existing one, if you like?

**Comment by dfed** [comment]
Thanks for the offer! Unfortunately, I can't vend a `.framework` I haven't built myself – since Valet deals with your application's secrets I need to have strict control over the build process. But I'd love a PR against Valet that adds the necessary build step to the `.framework` target for Carthage to include the dSYM. See the linked README above.

**Comment by mgroh** [comment]
This should be the default (with carthage 0.10): 
```
mgroh@mfg-mbp15:~/Code/mgroh/Valet|85d91c7
⇒  carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/hw/7k4s1f6951bf1j9w1pgksr0w0000gn/T/carthage-xcodebuild.KPxc53.log
*** Building scheme "Valet-Mac" in Valet.xcodeproj
*** Building scheme "Valet-iOS" in Valet.xcodeproj
mgroh@mfg-mbp15:~/Code/mgroh/Valet|85d91c7
⇒  ls Carthage/Build/iOS
66799F12-5366-37EB-A02A-657D1D9F3B23.bcsymbolmap Valet.framework
B8DC45FC-A816-3975-9DA5-CE67475F6C88.bcsymbolmap Valet.framework.dSYM
```

This also creates the currently missing bitcode files (as we discussed at length [on twitter](https://twitter.com/mgroh/status/672479319709499392)).

**Comment by dfed** [comment]
@mgroh so if I update my local carthage tool, then build/release a new version, everything should work?

**Comment by dfed** [comment]
Just updated the .framework on the 2.0.6. Same code, but now built with carthage 0.10. Please let me know if this fixes the above issue. If it does, I'll close this issue out.

**Comment by mgroh** [comment]
Yes, the release .zip now includes the .dSYM and .bcsymbolmap files.

**Comment by dfed** [comment]
Awesome. Thanks for the help! Closing this issue out
