### ISSUE TITLE
Keychain not accessible in setString

### ISSUE THREAD

**Issue by i-schuetz** [square/Valet#75]
This method suddenly started returning false while it working just a moment ago and I didn't make any changes. Testing with a device. The documentation says "@return NO if the keychain is not accessible." but why is it not accessible? Thanks.

**Comment by dfed** [comment]
When you are in this state, what does `canAccessKeychain` return?

**Comment by i-schuetz** [comment]
Can't test it as it started magically working again. I failed 5 times in a row and after a while I tried again and it worked. Will try it out when/if it happens again.

**Comment by dfed** [comment]
Check your console. And read the README. Running on device in the debugger sometimes doesn't work. It's an apple bug that we've documented

**Comment by i-schuetz** [comment]
I just read it, thanks. It could be that. There were no messages in the console.
