### ISSUE TITLE
Valet 3.0 (the one where we get Swifty)

### ISSUE THREAD

**Issue by EricMuller22** [square/Valet#84]
- [x] Rewrite Touch ID test app in Swift (to feel out pain points in the current Objective-C API)
- [x] Migrate unit tests to Swift
- [x] Move to Framework only builds and bump minimum iOS version to 8.0
- [x] Use .modulemaps to move to a mixed Swift/Objective-C framework
- [x] Swift API shim (using Objective-C implementation under the hood)
- [x] Objective-C interop test
- [x] Swift implementation

**Comment by EricMuller22** [comment]
cc @dfed anything else I should add?

**Comment by dfed** [comment]
- [ ] Cherry-pick 3ab0ea971766d7036f05e1c6a5c3f93bdcce92d0

**Comment by petrdvorak** [comment]
Guys, if I can comment on this: Please do a Swift support as a separate project on Github - like a 'square/SwiftyValet', or something. Objective-C is here to stay for some time and mixing these two languages in one project is IMO undesired even if it technically works.

**Comment by dfed** [comment]
Thanks for the feedback! Please note that we will be bumping the major version of Valet with this change. Apps that desire to use Objective-C libraries only can do so by locking to Valet's 2.* releases. If further development of Objective-C Valet is necessary or desired in the future, we have no qualms releasing dot updates to v2 off of a branch. Does that address your concerns?

**Comment by petrdvorak** [comment]
Yes, thank you. :)

**Comment by andrealufino** [comment]
Hello guys! I'm using Valet in one big project and I'd like to keep it, but I'd like to know if you plan to support Swift early or if this will be a long term thing. Could you give me news about this? 
Thanks and congratulations for the library!

**Comment by dfed** [comment]
Hi @andrealufino! We do current support Swift through the Swift-Objc bridge. But we do plan (despite the staleness of this issue) to release a new major version of this repo in Swift 4 this year.

**Comment by andrealufino** [comment]
This is a great news! You library it's well written and it's really simple to use. These are 2 fundamental features for a 3rd party framework. Congratulations! I will go on using it :)

**Comment by dfed** [comment]
PSA: We're planning on merging #80 & publishing v3.0 of Valet on March 2nd! **If you're interested in giving us feedback on #80, now is the time to do it.** We greatly appreciate everyone who has spent the time to review + improve this (quite massive) release.

**Comment by dfed** [comment]
This is in!

**Comment by EricMuller22** [comment]
![rick_dance](https://user-images.githubusercontent.com/1934212/37006280-7edcc7dc-208c-11e8-87b8-2de091f7c937.gif)
