### ISSUE TITLE
Store data = nil

### ISSUE THREAD

**Issue by remirobert** [square/Valet#86]
Hello,

I am using Valet to store sensible credential, like access token for authenticate the user in my app.
When I store it, I can't retrieve it, it's always nil.

```swift
class KeychainAccessManager {
    private var valetManager: VALValet?
    private static var sharedInstance = KeychainAccessManager()
    
    init() {
        self.valetManager = VALValet(identifier: "app.id", accessibility: .WhenUnlocked)
    }
    
    static func stringForKey(key: String) -> String? {
        print("[🔐] Keychain storage get {\(key)} manager : [\(self.sharedInstance.valetManager)]")
        
        return self.sharedInstance.valetManager?.stringForKey(key)
    }
    
    static func setString(string: String, key: String) {
        print("[🔐] Keychain storage set {\(string)} {\(key)} manager : [\(self.sharedInstance.valetManager)]")
        self.sharedInstance.valetManager?.setString(string, forKey: key)
    }
    
    static func removeString(key: String) {
        print("[🔐] Keychain storage remove {\(key)} manager : [\(self.sharedInstance.valetManager)]")
        self.sharedInstance.valetManager?.removeObjectForKey(key)
    }
}
```

I use this class to wrap the storage, but when I restart the app, I check if there is a token stored on it, it's always nil, so the user currently has to log every time.

Thanks in advance.

**Comment by dfed** [comment]
Could you be running into debugging issue 4 or 5 from the README?

What device and operating system are you running on? What version of Xcode are you using? What version of Valet are you using? If you call `canAccessKeychain` when you get and set the keychain values does it return `true`? Does `setString(_:forKey:)` return `true`?

If any of the above methods are returning `false`, please put a breakpoint in the method and let us know what error number you're seeing.

**Comment by dfed** [comment]
@remirobert any luck figuring it out?

**Comment by remirobert** [comment]
Yes and I am very sorry about that, I was.t debugging the right thing. It works perfectly !! 
Sorry for that I can now close this issue for ever.

Thanks for this library and the great work behind it.
