### ISSUE TITLE
Valet for Android

### ISSUE THREAD

**Issue by vanshg** [square/Valet#92]
Not an issue, but rather a suggestion:

It'd be awesome if you guys (Square) made something like this for Android. It is desperately needed (SharedPreferences is not encrypted, and the "Keychain" on Android is not meant for simple key-value pairs)

Love your guys's Open Source work!

**Comment by dfed** [comment]
Would be kinda nice wouldn't it? nerd-snipe: @JakeWharton and @pyricau

_ducks_

**Comment by JakeWharton** [comment]
https://github.com/square/whorlwind/

**Comment by vanshg** [comment]
But what if I don't want to use fingerprint? For example, a system of securely storing an API key, such that if someone had root access to their phone, they still could not get access to the API key (Because SharedPreferences works fine if the phone's not rooted, but as soon as it is rooted, anyone can take a look at any of the system files, and SP isn't encrypted, it's just plaintext AFAIK)

**Comment by JakeWharton** [comment]
Rooting obviates all encryption since the attacker can just inspect the
decrypted version from your app's memory. We have no plans at this time for
anything beyond whorlwind.

**Comment by vanshg** [comment]
Ah, true. Okay, well then, thanks for the input!
