### ISSUE TITLE
2.2.3 prebuilt binary is missing simulator architectures

### ISSUE THREAD

**Issue by erichoracek** [square/Valet#95]
```
$ dwarfdump --uuid Valet.framework/Valet 
UUID: 72092919-8C2C-37A4-9F37-79B65A8FE149 (armv7) Valet.framework/Valet
UUID: A212FAB9-F4F3-3BD7-B969-906EB663C99E (arm64) Valet.framework/Valet
```

It would appear that the simulator slices (`x86-64` and `i386`) are missing. On a normal framework built by Carthage, all are present.

**Comment by dfed** [comment]
Probably have a build of Carthage that doesn't play nicely with Xcode 8. Updating.

**Comment by dfed** [comment]
Should be fixed now.
