### ISSUE TITLE
Keychain error -34018 (errSecMissingEntitlement)

### ISSUE THREAD

**Issue by deepak4u2006** [square/Valet#96]
Always getting this issue, I have implemented Valet in 2 of my apps for one app it works like charm as promised. But for the 2nd app every time I get the above Keychain error. I am using xcode 8. Please guide as if not worked i will have to do a lot of rework.

I even tried creating a sample also for simple reading and writing operation on Keychain, but still getting the same error.
Thanks in advance.

**Comment by dfed** [comment]
Sounds like your development version of the app is missing the keychain entitlement. Xcode 8 requires debug builds be signed to access the keychain — sign your dev build just like you sign your App Store build.

I should add a note in the README about this.

**Comment by deepak4u2006** [comment]
Hi dfed, 
Thanks for reply. I think my code is properly signed as I able to create an .ipa file for remote deployment on device using my developer credentials.
"missing the keychain entitlement" I am not able to understand this.

With the same bundle Identifier and Provisioning profile one of my project is running fine with Valet, but for this one I don't know.

Kindly help.

**Comment by dfed** [comment]
This isn't a Valet issue. This is a configuration/signing issue in one of your apps — using a different keychain wrapper will to solve your issue.

Since you have one app that is working, I recommend opening up the Build Settings for each side-by-side and comparing. Read through the DEBUGGING section of the README as well.

I'm leaving this issue open to remind me to add the Xcode 8 issue to the README

**Comment by avnerbarr** [comment]
When I am running unit tests on an embedded framework target (which uses the keychain) I get the same error. Is there a workaround for that?

**Comment by dfed** [comment]
Make sure your unit test target has keychain entitlements.

**Comment by avnerbarr** [comment]
How do I do that?

**Comment by dfed** [comment]
Compare your test configuration to Valet's – between StackOverflow and our example you should be able to get there. Note that our tests are run within a host app that has entitlements.

Your lack of entitlements is a keychain issue, not a Valet issue.
